/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iucosoft.farmacy.gui;

import com.iucosoft.farmacy.dao.FinanceSubjectDaoIntf;
import com.iucosoft.farmacy.dao.impl.FinanceSubjectDaoImpl;
import com.iucosoft.farmacy.exceptions.ConnectionInterruptedException;
import com.iucosoft.farmacy.model.Client;
import com.iucosoft.farmacy.model.FinanceSubject;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Turkov S
 */
public class JDialogFinSubjSaveUpdate extends javax.swing.JDialog {

    /**
     * Creates new form JDialogClientsSaveUpdate
     */
    public JDialogFinSubjSaveUpdate(
            java.awt.Frame parent, boolean modal, Class finSubjectClass,
            String mode, FinanceSubject finSubj)
            throws ConnectionInterruptedException, InstantiationException, IllegalAccessException {
        super(parent, modal);
        initComponents();
        this.finSubjectClass = finSubjectClass;
        this.mode = mode;
        this.finSubj = finSubj;
        finSubjDao = new FinanceSubjectDaoImpl(finSubjectClass);
        initGuiComponents();
        setLocationRelativeTo(parent);
    }

    private void initGuiComponents() {
        if (mode == "add") {
            jButtonSaveAndClose.setText("Save & Close");
            jLabelId.setText("ID(generates automatically)");
            jButtonSaveAndNext.setEnabled(true);
            jButtonRevert.setEnabled(false);
        } else {
            jButtonSaveAndClose.setText("Update & Close");
            jLabelId.setText("ID(read only)");
            jButtonSaveAndNext.setEnabled(false);
            jButtonRevert.setEnabled(true);
            fillForm(finSubj);
        }
        jLabelName.setText(finSubjectClass.getSimpleName() + "'s name");
        jLabelAccount.setText(finSubjectClass.getSimpleName() + "'s account");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldAccount = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jButtonSaveAndNext = new javax.swing.JButton();
        jLabelAccount = new javax.swing.JLabel();
        jButtonRevert = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        jButtonClose = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        jButtonSaveAndClose = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAccountActionPerformed(evt);
            }
        });

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jButtonSaveAndNext.setText("Save & Next");
        jButtonSaveAndNext.setToolTipText("Save information and after add next");
        jButtonSaveAndNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAndNextActionPerformed(evt);
            }
        });

        jLabelAccount.setText("Account");

        jButtonRevert.setText("Revert");
        jButtonRevert.setToolTipText("Cancelling all modification to this record");
        jButtonRevert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRevertActionPerformed(evt);
            }
        });

        jTextFieldID.setEditable(false);
        jTextFieldID.setBackground(new java.awt.Color(204, 204, 255));

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jLabelName.setText("Name");

        jButtonSaveAndClose.setText("Save & Close");
        jButtonSaveAndClose.setToolTipText("Save information and close dialog");
        jButtonSaveAndClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAndCloseActionPerformed(evt);
            }
        });

        jLabelId.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSaveAndClose)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonSaveAndNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRevert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonClose))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelId, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelName)
                                .addComponent(jLabelAccount))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(jTextFieldAccount)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAccount)
                    .addComponent(jTextFieldAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRevert)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonSaveAndClose)
                    .addComponent(jButtonSaveAndNext))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonSaveAndNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAndNextActionPerformed
        addFinanceSubject();
        clearForm();
    }//GEN-LAST:event_jButtonSaveAndNextActionPerformed

    private void jButtonSaveAndCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAndCloseActionPerformed
        if (mode == "add") {
            addFinanceSubject();
        } else {
            updateFinanceSubject();
        }
        dispose();
    }//GEN-LAST:event_jButtonSaveAndCloseActionPerformed

    private void jButtonRevertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRevertActionPerformed
        fillForm(finSubjDao.findFinSubjectById(Integer.parseInt(jTextFieldID.getText())));
    }//GEN-LAST:event_jButtonRevertActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        jTextFieldAccount.requestFocus();
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAccountActionPerformed
        jButtonSaveAndClose.requestFocus();
    }//GEN-LAST:event_jTextFieldAccountActionPerformed

    private void clearForm() {
        jTextFieldID.setText("");
        jTextFieldName.setText("");
        jTextFieldAccount.setText("");
    }

    private void fillForm(FinanceSubject finSubj) {
        jTextFieldID.setText("" + finSubj.getId());
        jTextFieldName.setText(finSubj.getName());
        jTextFieldAccount.setText(finSubj.getAccount());
    }

    private void addFinanceSubject() {
        finSubj.setName(jTextFieldName.getText());
        finSubj.setAccount(jTextFieldAccount.getText());
        finSubj.setId(finSubjDao.addFinSubject(finSubj));
    }

    private void updateFinanceSubject() {
        finSubj.setId(Integer.parseInt(jTextFieldID.getText()));
        finSubj.setName(jTextFieldName.getText());
        finSubj.setAccount(jTextFieldAccount.getText());
        finSubjDao.updateFinSubject(finSubj);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogFinSubjSaveUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogFinSubjSaveUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogFinSubjSaveUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogFinSubjSaveUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    JDialogFinSubjSaveUpdate dialog = new JDialogFinSubjSaveUpdate(new javax.swing.JFrame(), true, new Client().getClass(), "save", new Client());
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(JDialogFinSubjSaveUpdate.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonRevert;
    private javax.swing.JButton jButtonSaveAndClose;
    private javax.swing.JButton jButtonSaveAndNext;
    private javax.swing.JLabel jLabelAccount;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JTextField jTextFieldAccount;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
    Class finSubjectClass;
    FinanceSubject finSubj;
    String mode;
    FinanceSubjectDaoIntf finSubjDao;
}
