/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iucosoft.farmacy.gui;

import com.iucosoft.farmacy.dao.FarmacyBalanceDaoIntf;
import com.iucosoft.farmacy.dao.impl.FarmacyBalanceDaoImpl;
import com.iucosoft.farmacy.db.Config;
import com.iucosoft.farmacy.utils.MD5;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Turkov S
 */
public class JDialogSettings extends javax.swing.JDialog {

    /**
     * Creates new form JDialogSettings
     */
    public JDialogSettings(java.awt.Frame parent, boolean modal, StringBuilder mode) throws Exception {
        super(parent, modal);
        this.mode = mode;
        initComponents();
        initGuiComponents();
        setLocationRelativeTo(parent);
    }

    private void initGuiComponents() throws Exception {
        Properties props = Config.loadProperties();
        jCheckBoxOpenFile.setSelected(Boolean.valueOf(props.getProperty("openfile")));
        jRadioButtonJDatePicker.setSelected(Boolean.valueOf(props.getProperty("jdatepicker")));
        jRadioButtonJSpinner.setSelected(Boolean.valueOf(props.getProperty("jspinner")));
        jTextFieldExcel.setText(props.getProperty("xlsprogram"));
        jTextFieldPdf.setText(props.getProperty("pdfprogram"));
        jTextFieldCSV.setText(props.getProperty("csvprogram"));
        jComboBoxCSVSeparator.setSelectedItem(props.getProperty("csvseparator"));
        farmBalanceDao = new FarmacyBalanceDaoImpl();
        jButtonClearManagerPassword.setEnabled(false);
        jTextFieldFarmacyName.setText(farmBalanceDao.getFarmacyName());
        if (mode.toString().equals("Manager")) {
            jPanelFarmacyAccount.setEnabled(false);
            jPanelStockBalance.setEnabled(false);
            jRadioButtonAllowNegativeBalance.setEnabled(false);
            jRadioButtonRestrictNegativeBalance.setEnabled(false);
            jRadioButtonAllowStockNegativeBalance.setEnabled(false);
            jRadioButtonRestrictStockNegativeBalance.setEnabled(false);
            jTextFieldFarmacyName.setEnabled(false);
        }
        boolean permissions[] = farmBalanceDao.getPermissions();
        jRadioButtonAllowNegativeBalance.setSelected(permissions[0]);
        jRadioButtonAllowStockNegativeBalance.setSelected(permissions[1]);
        DefaultComboBoxModel<String> modelSkins = new DefaultComboBoxModel<>();
        UIManager.LookAndFeelInfo[] looks = UIManager.getInstalledLookAndFeels();
        for (UIManager.LookAndFeelInfo look : looks) {
            modelSkins.addElement(look.getName());
        }
        modelSkins.setSelectedItem(props.getProperty("skin"));
        jComboBoxProgramSkin.setModel(modelSkins);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxOpenFile = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldExcel = new javax.swing.JTextField();
        jTextFieldPdf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCSV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxCSVSeparator = new javax.swing.JComboBox();
        jPanelStockBalance = new javax.swing.JPanel();
        jRadioButtonRestrictStockNegativeBalance = new javax.swing.JRadioButton();
        jRadioButtonAllowStockNegativeBalance = new javax.swing.JRadioButton();
        jPanelFarmacyAccount = new javax.swing.JPanel();
        jRadioButtonRestrictNegativeBalance = new javax.swing.JRadioButton();
        jRadioButtonAllowNegativeBalance = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldFarmacyName = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxUsers = new javax.swing.JComboBox();
        jPasswordOldPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordNewPassword = new javax.swing.JPasswordField();
        jPasswordConfirmNewPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jButtonSavePassword = new javax.swing.JButton();
        jButtonClearManagerPassword = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonJDatePicker = new javax.swing.JRadioButton();
        jRadioButtonJSpinner = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jButtonDefaultSettings = new javax.swing.JButton();
        jButtonSaveSettings = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxProgramSkin = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Export Settings"));

        jCheckBoxOpenFile.setText("Open exported file");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iucosoft/farmacy/gui/icons/1423070960_Microsoft Office Excel32.png"))); // NOI18N
        jLabel1.setToolTipText("Excel files");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iucosoft/farmacy/gui/icons/1423071193_Adobe Acrobat Professional32.png"))); // NOI18N
        jLabel2.setToolTipText("PDF files");

        jLabel3.setText("Only in Linux OS (program name to open files)");

        jTextFieldExcel.setText("libreoffice -calc");

        jTextFieldPdf.setText("gedit");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iucosoft/farmacy/gui/icons/file_csv32.png"))); // NOI18N
        jLabel8.setToolTipText("PDF files");

        jTextFieldCSV.setText("libreoffice -calc");
        jTextFieldCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCSVActionPerformed(evt);
            }
        });

        jLabel7.setText("CSV separator");

        jComboBoxCSVSeparator.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ";", ",", "-", "/", ".", "\\", "'", "`", "|", ":" }));

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldExcel)
                                .addComponent(jTextFieldPdf)
                                .addComponent(jTextFieldCSV)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBoxOpenFile)
                                .addComponent(jLabel3)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBoxCSVSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxOpenFile)
                    .addGap(11, 11, 11)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldExcel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8)
                        .addComponent(jTextFieldCSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jComboBoxCSVSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            );

            jPanelStockBalance.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock's balance settings"));

            buttonGroup3.add(jRadioButtonRestrictStockNegativeBalance);
            jRadioButtonRestrictStockNegativeBalance.setSelected(true);
            jRadioButtonRestrictStockNegativeBalance.setText("Restrict negative balance");
            jRadioButtonRestrictStockNegativeBalance.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jRadioButtonRestrictStockNegativeBalanceActionPerformed(evt);
                }
            });

            buttonGroup3.add(jRadioButtonAllowStockNegativeBalance);
            jRadioButtonAllowStockNegativeBalance.setText("Allow negative balance");
            jRadioButtonAllowStockNegativeBalance.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jRadioButtonAllowStockNegativeBalanceActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanelStockBalanceLayout = new javax.swing.GroupLayout(jPanelStockBalance);
            jPanelStockBalance.setLayout(jPanelStockBalanceLayout);
            jPanelStockBalanceLayout.setHorizontalGroup(
                jPanelStockBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelStockBalanceLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelStockBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButtonAllowStockNegativeBalance)
                        .addComponent(jRadioButtonRestrictStockNegativeBalance))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanelStockBalanceLayout.setVerticalGroup(
                jPanelStockBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStockBalanceLayout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(jRadioButtonAllowStockNegativeBalance)
                    .addGap(11, 11, 11)
                    .addComponent(jRadioButtonRestrictStockNegativeBalance)
                    .addContainerGap())
            );

            jPanelFarmacyAccount.setBorder(javax.swing.BorderFactory.createTitledBorder("Farmacy account settings"));

            buttonGroup2.add(jRadioButtonRestrictNegativeBalance);
            jRadioButtonRestrictNegativeBalance.setSelected(true);
            jRadioButtonRestrictNegativeBalance.setText("Restrict negative balance");
            jRadioButtonRestrictNegativeBalance.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jRadioButtonRestrictNegativeBalanceActionPerformed(evt);
                }
            });

            buttonGroup2.add(jRadioButtonAllowNegativeBalance);
            jRadioButtonAllowNegativeBalance.setText("Allow negative balance");
            jRadioButtonAllowNegativeBalance.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jRadioButtonAllowNegativeBalanceActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanelFarmacyAccountLayout = new javax.swing.GroupLayout(jPanelFarmacyAccount);
            jPanelFarmacyAccount.setLayout(jPanelFarmacyAccountLayout);
            jPanelFarmacyAccountLayout.setHorizontalGroup(
                jPanelFarmacyAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFarmacyAccountLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelFarmacyAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButtonAllowNegativeBalance)
                        .addComponent(jRadioButtonRestrictNegativeBalance))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanelFarmacyAccountLayout.setVerticalGroup(
                jPanelFarmacyAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFarmacyAccountLayout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(jRadioButtonAllowNegativeBalance)
                    .addGap(11, 11, 11)
                    .addComponent(jRadioButtonRestrictNegativeBalance)
                    .addContainerGap())
            );

            jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Farmacy name"));

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTextFieldFarmacyName, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldFarmacyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
            jPanel6.setLayout(jPanel6Layout);
            jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanelStockBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelFarmacyAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanelFarmacyAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanelStockBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Users"));

            jComboBoxUsers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrator", "Manager" }));
            jComboBoxUsers.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    jComboBoxUsersItemStateChanged(evt);
                }
            });

            jLabel4.setText("Old password");

            jLabel5.setText("New password");

            jLabel6.setText("Confirm new password");

            jButtonSavePassword.setText("Save password");
            jButtonSavePassword.setToolTipText("Save new Password");
            jButtonSavePassword.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonSavePasswordActionPerformed(evt);
                }
            });

            jButtonClearManagerPassword.setText("Clear");
            jButtonClearManagerPassword.setToolTipText("Clear Manager Password");
            jButtonClearManagerPassword.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonClearManagerPasswordActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jComboBoxUsers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPasswordOldPassword)
                .addComponent(jPasswordNewPassword)
                .addComponent(jPasswordConfirmNewPassword)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGap(0, 0, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addComponent(jButtonClearManagerPassword)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButtonSavePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jComboBoxUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPasswordOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPasswordNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPasswordConfirmNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSavePassword)
                        .addComponent(jButtonClearManagerPassword))
                    .addContainerGap())
            );

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Date component"));
            jPanel1.setToolTipText("Set date chooser");

            buttonGroup1.add(jRadioButtonJDatePicker);
            jRadioButtonJDatePicker.setSelected(true);
            jRadioButtonJDatePicker.setText("Picker");

            buttonGroup1.add(jRadioButtonJSpinner);
            jRadioButtonJSpinner.setText("Spinner");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButtonJSpinner)
                        .addComponent(jRadioButtonJDatePicker))
                    .addContainerGap(110, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jRadioButtonJDatePicker)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jRadioButtonJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
                    .addGap(2, 2, 2))
            );

            jButtonDefaultSettings.setText("Restore defaults");
            jButtonDefaultSettings.setToolTipText("");
            jButtonDefaultSettings.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonDefaultSettingsActionPerformed(evt);
                }
            });

            jButtonSaveSettings.setText("Save settings");
            jButtonSaveSettings.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonSaveSettingsActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
            jPanel7.setLayout(jPanel7Layout);
            jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonDefaultSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSaveSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonDefaultSettings, jButtonSaveSettings});

            jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButtonSaveSettings)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButtonDefaultSettings)
                    .addContainerGap())
            );

            jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Program skin(need to restart)"));

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jComboBoxProgramSkin, javax.swing.GroupLayout.Alignment.TRAILING, 0, 177, Short.MAX_VALUE)
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jComboBoxProgramSkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
            jPanel8.setLayout(jPanel8Layout);
            jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButtonDefaultSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDefaultSettingsActionPerformed
        jCheckBoxOpenFile.setSelected(false);
        jRadioButtonJDatePicker.setSelected(true);
        jTextFieldExcel.setText("ooffice --calc");
        jTextFieldCSV.setText("ooffice --calc");
        jTextFieldPdf.setText("evince");
        jComboBoxCSVSeparator.setSelectedIndex(0);
        jComboBoxProgramSkin.setSelectedItem("Nimbus");
        if (!mode.toString().equals("Manager")) {
            jTextFieldFarmacyName.setText("Farmacie IUCOSOFT");
        }
        saveSettings();
    }//GEN-LAST:event_jButtonDefaultSettingsActionPerformed

    private void saveSettings() {
        Properties props = Config.loadProperties();
        props.setProperty("jspinner", Boolean.toString(jRadioButtonJSpinner.isSelected()));
        props.setProperty("jdatepicker", Boolean.toString(jRadioButtonJDatePicker.isSelected()));
        props.setProperty("xlsprogram", jTextFieldExcel.getText());
        props.setProperty("pdfprogram", jTextFieldPdf.getText());
        props.setProperty("csvprogram", jTextFieldCSV.getText());
        props.setProperty("csvseparator", (String) jComboBoxCSVSeparator.getSelectedItem());
        props.setProperty("openfile", Boolean.toString(jCheckBoxOpenFile.isSelected()));
        props.setProperty("skin", (String) jComboBoxProgramSkin.getSelectedItem());
        Config.saveProperties(props);
        farmBalanceDao.setFarmacyName(jTextFieldFarmacyName.getText());
        //JOptionPane.showMessageDialog(this,"Properties succesfully saved");
    }


    private void jButtonSaveSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveSettingsActionPerformed
        saveSettings();
        dispose();
    }//GEN-LAST:event_jButtonSaveSettingsActionPerformed

    private void clearPasswordsFields() {
        jPasswordOldPassword.setText("");
        jPasswordNewPassword.setText("");
        jPasswordConfirmNewPassword.setText("");
    }

    private void jButtonSavePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSavePasswordActionPerformed

        new Runnable() {
            @Override
            public void run() {
                char[] oldPassword = jPasswordOldPassword.getPassword();
                char[] newPassword = jPasswordNewPassword.getPassword();
                if (!new String(newPassword).equals(new String(jPasswordConfirmNewPassword.getPassword()))) {
                    JOptionPane.showMessageDialog(null, "Entered passwords doesn't match");
                    return;
                }
                switch (jComboBoxUsers.getSelectedIndex()) {

                    case 0:
                        if (!MD5.getMD5(oldPassword).equals(new String(farmBalanceDao.getAdminPassword()))) {
                            JOptionPane.showMessageDialog(null, "Old password is wrong");
                            //if you want to reset admin password comment 607 line and line 184 JDialogAuthentification.java
                            //and uncomment 608 line
                            return;
                           // farmBalanceDao.setAdminPassword(MD5.getMD5(newPassword));
                        } else {
                            farmBalanceDao.setAdminPassword(MD5.getMD5(newPassword));
                        }
                        break;

                    case 1:
                        if (!MD5.getMD5(oldPassword).equals(new String(farmBalanceDao.getManagerPassword()))) {
                            JOptionPane.showMessageDialog(null, "Old password is wrong");
                            return;
                        } else {
                            farmBalanceDao.setManagerPassword(MD5.getMD5(newPassword));
                        }
                }
                JOptionPane.showMessageDialog(null, "Password was succesfully updated");
                clearPasswordsFields();
            }
        }.run();
    }//GEN-LAST:event_jButtonSavePasswordActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        jButtonSaveSettingsActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    private void jButtonClearManagerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearManagerPasswordActionPerformed
        if (mode.toString().equals("Administrator")) {
            farmBalanceDao.setManagerPassword(MD5.getMD5("".toCharArray()));
            JOptionPane.showMessageDialog(null, "Manager password cleared");
            clearPasswordsFields();
        }
    }//GEN-LAST:event_jButtonClearManagerPasswordActionPerformed

    private void jComboBoxUsersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxUsersItemStateChanged
        if (jComboBoxUsers.getSelectedIndex() == 0) {
            jButtonClearManagerPassword.setEnabled(false);
        } else {
            if (mode.toString().equals("Administrator")) {
                jButtonClearManagerPassword.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jComboBoxUsersItemStateChanged

    private void jRadioButtonRestrictNegativeBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRestrictNegativeBalanceActionPerformed
        try {
            farmBalanceDao.RestrictNegativeBalance();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            jRadioButtonAllowNegativeBalance.setSelected(true);
        }
    }//GEN-LAST:event_jRadioButtonRestrictNegativeBalanceActionPerformed

    private void jRadioButtonAllowNegativeBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAllowNegativeBalanceActionPerformed
        farmBalanceDao.AllowNegativeBalance();
    }//GEN-LAST:event_jRadioButtonAllowNegativeBalanceActionPerformed

    private void jRadioButtonRestrictStockNegativeBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRestrictStockNegativeBalanceActionPerformed
        try {
            farmBalanceDao.RestrictStockNegativeBalance();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            jRadioButtonAllowStockNegativeBalance.setSelected(true);
        }
    }//GEN-LAST:event_jRadioButtonRestrictStockNegativeBalanceActionPerformed

    private void jRadioButtonAllowStockNegativeBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAllowStockNegativeBalanceActionPerformed
        farmBalanceDao.AllowStockNegativeBalance();
    }//GEN-LAST:event_jRadioButtonAllowStockNegativeBalanceActionPerformed

    private void jTextFieldCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    JDialogSettings dialog = new JDialogSettings(new javax.swing.JFrame(), true, null);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(JDialogSettings.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButtonClearManagerPassword;
    private javax.swing.JButton jButtonDefaultSettings;
    private javax.swing.JButton jButtonSavePassword;
    private javax.swing.JButton jButtonSaveSettings;
    private javax.swing.JCheckBox jCheckBoxOpenFile;
    private javax.swing.JComboBox jComboBoxCSVSeparator;
    private javax.swing.JComboBox jComboBoxProgramSkin;
    private javax.swing.JComboBox jComboBoxUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelFarmacyAccount;
    private javax.swing.JPanel jPanelStockBalance;
    private javax.swing.JPasswordField jPasswordConfirmNewPassword;
    private javax.swing.JPasswordField jPasswordNewPassword;
    private javax.swing.JPasswordField jPasswordOldPassword;
    private javax.swing.JRadioButton jRadioButtonAllowNegativeBalance;
    private javax.swing.JRadioButton jRadioButtonAllowStockNegativeBalance;
    private javax.swing.JRadioButton jRadioButtonJDatePicker;
    private javax.swing.JRadioButton jRadioButtonJSpinner;
    private javax.swing.JRadioButton jRadioButtonRestrictNegativeBalance;
    private javax.swing.JRadioButton jRadioButtonRestrictStockNegativeBalance;
    private javax.swing.JTextField jTextFieldCSV;
    private javax.swing.JTextField jTextFieldExcel;
    private javax.swing.JTextField jTextFieldFarmacyName;
    private javax.swing.JTextField jTextFieldPdf;
    // End of variables declaration//GEN-END:variables

    FarmacyBalanceDaoIntf farmBalanceDao;
    StringBuilder mode;
}
