/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iucosoft.farmacy.gui;

import com.iucosoft.farmacy.dao.CategoryDaoIntf;
import com.iucosoft.farmacy.dao.MedicamentDaoIntf;
import com.iucosoft.farmacy.dao.impl.CategoryDaoImpl;
import com.iucosoft.farmacy.dao.impl.MedicamentDaoImpl;
import com.iucosoft.farmacy.exceptions.OverSizeFieldException;
import com.iucosoft.farmacy.gui.models.CategoryComboBoxModel;
import com.iucosoft.farmacy.model.Category;
import com.iucosoft.farmacy.model.Medicament;
import static java.awt.event.MouseEvent.BUTTON1;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Turkov S
 */
public class JDialogMedicamentSaveUpdate extends javax.swing.JDialog {

    /**
     * Creates new form JDialogMedicament
     */
    public JDialogMedicamentSaveUpdate(java.awt.Frame parent, boolean modal, String mode, Medicament medicament, File dir) throws Exception {
        super(parent, modal);
        initComponents();
        this.dir = dir;
        this.mode = mode;
        this.medicament = medicament;
        catDao = new CategoryDaoImpl();
        medDao = new MedicamentDaoImpl();
        initGuiComponents();
        setLocationRelativeTo(parent);
    }

    private void initGuiComponents() throws Exception {
        aCategoryComboBoxModel = new CategoryComboBoxModel();
        jComboBoxCategories.setModel(aCategoryComboBoxModel);
        if (mode == "Save") {
            jButtonSaveAndClose.setText("Save & Close");
            jLabelId.setText("ID(generates automatically)");
            jButtonSaveAndNext.setEnabled(true);
            jButtonRevert.setEnabled(false);
        } else {
            jButtonSaveAndClose.setText("Update & Close");
            jLabelId.setText("ID(read only)");
            jButtonSaveAndNext.setEnabled(false);
            jButtonRevert.setEnabled(true);
            fillForm(medicament);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSaveAndClose = new javax.swing.JButton();
        jButtonRevert = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jButtonSaveAndNext = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelMedIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldNameMedicament = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jTextFieldIdMedicament = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCategories = new javax.swing.JComboBox();
        jTextFieldLatinName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        jButtonSaveAndClose.setText("Save & Close");
        jButtonSaveAndClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAndCloseActionPerformed(evt);
            }
        });

        jButtonRevert.setText("Revert");
        jButtonRevert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRevertActionPerformed(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonSaveAndNext.setText("Save & Next");
        jButtonSaveAndNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAndNextActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setMaximumSize(new java.awt.Dimension(190, 90));
        jPanel2.setMinimumSize(new java.awt.Dimension(190, 90));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(190, 90));

        jLabelMedIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMedIcon.setText("D'Click to load image(85x185)");
        jLabelMedIcon.setToolTipText("Click to change");
        jLabelMedIcon.setMaximumSize(new java.awt.Dimension(185, 85));
        jLabelMedIcon.setMinimumSize(new java.awt.Dimension(185, 85));
        jLabelMedIcon.setPreferredSize(new java.awt.Dimension(185, 85));
        jLabelMedIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelMedIconMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelMedIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelMedIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setText("Medicament image");

        jTextFieldNameMedicament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameMedicamentActionPerformed(evt);
            }
        });

        jLabel3.setText("Category of Medicament");

        jLabelId.setText("ID");

        jTextFieldIdMedicament.setEditable(false);
        jTextFieldIdMedicament.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setText("Latin name of medicament");

        jComboBoxCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriesActionPerformed(evt);
            }
        });

        jTextFieldLatinName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLatinNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Name of Medicament");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldIdMedicament, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNameMedicament, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxCategories, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldLatinName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(jTextFieldIdMedicament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNameMedicament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldLatinName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSaveAndClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSaveAndNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRevert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClose))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveAndClose)
                    .addComponent(jButtonRevert)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonSaveAndNext))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonRevertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRevertActionPerformed
        fillForm(medDao.findByIdMedicament(Integer.parseInt(jTextFieldIdMedicament.getText())));
    }//GEN-LAST:event_jButtonRevertActionPerformed

    private void saveMedicament() throws OverSizeFieldException {
        Category categ = (Category) jComboBoxCategories.getSelectedItem();
        medicament.setNameMedicament(jTextFieldNameMedicament.getText());
        medicament.setIdCategory(categ.getIdCategory());
        medicament.setLatinNameMedicament(jTextFieldLatinName.getText());
        medicament.setIdMedicament(medDao.createMedicament(medicament));
    }

    private void updateMedicament() throws OverSizeFieldException {
        Category categ = (Category) jComboBoxCategories.getSelectedItem();
        medicament.setIdCategory(Integer.parseInt(jTextFieldIdMedicament.getText()));
        medicament.setNameMedicament(jTextFieldNameMedicament.getText());
        medicament.setIdCategory(categ.getIdCategory());
        medicament.setLatinNameMedicament(jTextFieldLatinName.getText());
        medDao.updateMedicament(medicament);
    }

    private void clearForm() {
        jTextFieldNameMedicament.setText("");
        jComboBoxCategories.setSelectedIndex(0);
        jTextFieldLatinName.setText("");
        jLabelMedIcon.setIcon(new ImageIcon());
        jLabelMedIcon.setText("D'Click to load image(85x185)");
    }

    void fillForm(Medicament medicament) {
        jTextFieldIdMedicament.setText("" + medicament.getIdMedicament());
        jTextFieldNameMedicament.setText(medicament.getNameMedicament());
        if (medicament.getIdCategory() > 0) {
            jComboBoxCategories.setSelectedItem(catDao.findByIdCategory(medicament.getIdCategory()));
        } else {
            jComboBoxCategories.setSelectedIndex(0);
        }
        jTextFieldLatinName.setText(medicament.getLatinNameMedicament());
        if (medicament.getIconMedicament() != null) {
            jLabelMedIcon.setText("");
            jLabelMedIcon.setIcon(new ImageIcon(medicament.getIconMedicament()));
        } else {
            jLabelMedIcon.setIcon(new ImageIcon());
            jLabelMedIcon.setText("D'Click to load image(85x185)");
        }
    }


    private void jButtonSaveAndCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAndCloseActionPerformed
        try {
            if (mode == "Save") {
                saveMedicament();

            } else {
                updateMedicament();
            }
        } catch (OverSizeFieldException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        dispose();
    }//GEN-LAST:event_jButtonSaveAndCloseActionPerformed

    private void jButtonSaveAndNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAndNextActionPerformed
        try {
            saveMedicament();
            clearForm();
        } catch (OverSizeFieldException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSaveAndNextActionPerformed

    private void loadMedIcon() {
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(jFileChooser.FILES_ONLY);
        jFileChooser.setDialogTitle(jTextFieldNameMedicament.getText().toUpperCase() + ".Please choose a file to open. Max size is 185x85. 65Kb MAX");
        jFileChooser.removeChoosableFileFilter(jFileChooser.getFileFilter());
        FileFilter filter = new FileNameExtensionFilter("Images", "jpg", "jpeg", "gif", "png");
//      jFileChooser.addChoosableFileFilter(filter);
        jFileChooser.setFileFilter(filter);
        if (dir != null) {
            jFileChooser.setCurrentDirectory(dir);
        }
        int rez = jFileChooser.showOpenDialog(this);
        if (rez == JFileChooser.APPROVE_OPTION) {
            File f = jFileChooser.getSelectedFile();
            if (f != null) {
                try {
                    dir = f.toPath().getParent().toFile();
                    type = jFileChooser.getFileFilter().getDescription();
                    medicament.setIconMedicament(Files.readAllBytes(f.toPath()));
                    jLabelMedIcon.setIcon(new ImageIcon(medicament.getIconMedicament()));
                    jLabelMedIcon.setText("");
                } catch (IOException ex) {
                    Logger.getLogger(JDialogMedicamentSaveUpdate.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                jLabelMedIcon.setIcon(new ImageIcon());
                jLabelMedIcon.setText("D'Click to load image(85x185)");
            }
        }
    }

    private void jTextFieldLatinNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLatinNameActionPerformed
        jButtonSaveAndClose.requestFocus();
    }//GEN-LAST:event_jTextFieldLatinNameActionPerformed

    private void jComboBoxCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriesActionPerformed
        jTextFieldLatinName.requestFocus();
    }//GEN-LAST:event_jComboBoxCategoriesActionPerformed

    private void jTextFieldNameMedicamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameMedicamentActionPerformed
        jComboBoxCategories.requestFocus();
    }//GEN-LAST:event_jTextFieldNameMedicamentActionPerformed

    private void jLabelMedIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMedIconMousePressed
        if (evt.getButton() == BUTTON1 && evt.getClickCount() == 2) {
            loadMedIcon();
        }
    }//GEN-LAST:event_jLabelMedIconMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogMedicamentSaveUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogMedicamentSaveUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogMedicamentSaveUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogMedicamentSaveUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    JDialogMedicamentSaveUpdate dialog = new JDialogMedicamentSaveUpdate(new javax.swing.JFrame(), true, "Save", null, null);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(JDialogMedicamentSaveUpdate.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonRevert;
    private javax.swing.JButton jButtonSaveAndClose;
    private javax.swing.JButton jButtonSaveAndNext;
    private javax.swing.JComboBox jComboBoxCategories;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMedIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldIdMedicament;
    private javax.swing.JTextField jTextFieldLatinName;
    private javax.swing.JTextField jTextFieldNameMedicament;
    // End of variables declaration//GEN-END:variables

    CategoryComboBoxModel aCategoryComboBoxModel;
    CategoryDaoIntf catDao;
    MedicamentDaoIntf medDao;
    String mode;
    Medicament medicament;
    File dir;
    String type;
}
