/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iucosoft.farmacy.gui;

import com.iucosoft.farmacy.dao.FinanceSubjectDaoIntf;
import com.iucosoft.farmacy.dao.impl.FinanceSubjectDaoImpl;
import com.iucosoft.farmacy.exceptions.ConnectionInterruptedException;
import com.iucosoft.farmacy.exceptions.DeletingException;
import com.iucosoft.farmacy.gui.models.FinSubjTableModel;
import com.iucosoft.farmacy.model.FinanceSubject;
import static com.iucosoft.farmacy.utils.Util.selectRowInTable;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Turkov S
 */
public class JFrameFinSubjects extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(JFrameFinSubjects.class.getName());

    /**
     * Creates new form FrameClients
     */
    public JFrameFinSubjects(Class className) throws Exception {
        initComponents();
        finSubjectClass = className;
        finSubjDao = new FinanceSubjectDaoImpl(finSubjectClass);
        initGuiComponents();
        addListeners();
        setLocationRelativeTo(null);
    }

    private void initGuiComponents() throws Exception {
        String textMenus = finSubjectClass.getSimpleName();
        jButtonAddClientSupplier.setText("Add New " + textMenus);
        jButtonEditClientSupplier.setText("Edit " + textMenus);
        jButtonRemoveClientSupllier.setText("Remove " + textMenus);
        jMenuItemAdd.setText("Add " + textMenus);
        jMenuItemEdit.setText("Edit " + textMenus);
        jMenuItemRemove.setText("Remove " + textMenus);
        jPanelSearch.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "Search for " + textMenus));
        aFinSubjTableModel = new FinSubjTableModel(finSubjectClass);
        jTableFinSubjects.setModel(aFinSubjTableModel);
        jTableFinSubjects.getColumnModel().getColumn(0).setPreferredWidth(15);
        jTableFinSubjects.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableFinSubjects.getColumnModel().getColumn(2).setPreferredWidth(100);
    }

    private void addListeners() {
        jTableFinSubjects.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
                int selectedRow = jTableFinSubjects.getSelectedRow();
                if (selectedRow >= 0) {
                    int id = (Integer) jTableFinSubjects.getValueAt(selectedRow, 0);
                    selectedFinSubj = finSubjDao.findFinSubjectById(id);
                } else {
                    selectedFinSubj = null;
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuTable = new javax.swing.JPopupMenu();
        jMenuItemAdd = new javax.swing.JMenuItem();
        jMenuItemEdit = new javax.swing.JMenuItem();
        jMenuItemRemove = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButtonAddClientSupplier = new javax.swing.JButton();
        jButtonRemoveClientSupllier = new javax.swing.JButton();
        jButtonEditClientSupplier = new javax.swing.JButton();
        jPanelSearch = new javax.swing.JPanel();
        jTextFieldNameClientSupplier = new javax.swing.JTextField();
        jTextFieldAccountClientSupplier = new javax.swing.JTextField();
        jButtonClearForm = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFinSubjects = new javax.swing.JTable();

        jMenuItemAdd.setText("Add");
        jMenuItemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddActionPerformed(evt);
            }
        });
        jPopupMenuTable.add(jMenuItemAdd);

        jMenuItemEdit.setText("Edit");
        jMenuItemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditActionPerformed(evt);
            }
        });
        jPopupMenuTable.add(jMenuItemEdit);

        jMenuItemRemove.setText("Remove");
        jMenuItemRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoveActionPerformed(evt);
            }
        });
        jPopupMenuTable.add(jMenuItemRemove);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonAddClientSupplier.setText("Add New");
        jButtonAddClientSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddClientSupplierActionPerformed(evt);
            }
        });

        jButtonRemoveClientSupllier.setText("Remove");
        jButtonRemoveClientSupllier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveClientSupllierActionPerformed(evt);
            }
        });

        jButtonEditClientSupplier.setText("Edit");
        jButtonEditClientSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditClientSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddClientSupplier)
                    .addComponent(jButtonEditClientSupplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemoveClientSupllier, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAddClientSupplier, jButtonEditClientSupplier, jButtonRemoveClientSupllier});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddClientSupplier)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditClientSupplier)
                .addGap(18, 18, 18)
                .addComponent(jButtonRemoveClientSupllier)
                .addContainerGap())
        );

        jPanelSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search"));

        jTextFieldNameClientSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNameClientSupplierKeyReleased(evt);
            }
        });

        jTextFieldAccountClientSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAccountClientSupplierKeyReleased(evt);
            }
        });

        jButtonClearForm.setText("Clear");
        jButtonClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSearchLayout = new javax.swing.GroupLayout(jPanelSearch);
        jPanelSearch.setLayout(jPanelSearchLayout);
        jPanelSearchLayout.setHorizontalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldAccountClientSupplier, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNameClientSupplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClearForm)
                .addContainerGap())
        );
        jPanelSearchLayout.setVerticalGroup(
            jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNameClientSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClearForm))
                .addGap(18, 18, 18)
                .addComponent(jTextFieldAccountClientSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jTableFinSubjects.setAutoCreateRowSorter(true);
        jTableFinSubjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "FinSubject Name", "FinSubject Account"
            }
        ));
        jTableFinSubjects.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTableFinSubjects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableFinSubjects.getTableHeader().setReorderingAllowed(false);
        jTableFinSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableFinSubjectsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableFinSubjectsMouseReleased(evt);
            }
        });
        jTableFinSubjects.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableFinSubjectsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFinSubjects);
        if (jTableFinSubjects.getColumnModel().getColumnCount() > 0) {
            jTableFinSubjects.getColumnModel().getColumn(0).setMinWidth(30);
            jTableFinSubjects.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableFinSubjects.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanelSearch});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonClose)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDialogFinSubjectsCreateAndShow(JDialogFinSubjSaveUpdate jDialogClientsSaveUpdate, Class finSubjectClass, FinanceSubject finSubj) {
        if (jDialogClientsSaveUpdate != null) {
            jDialogClientsSaveUpdate = null;
        }
        String type = null;
        if (finSubj == null) {
            try {
                finSubj = (FinanceSubject) finSubjectClass.newInstance();
                type = "add";
            } catch (InstantiationException ex) {
                Logger.getLogger(JFrameFinSubjects.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(JFrameFinSubjects.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            type = "edit";
        }
        try {
            jDialogClientsSaveUpdate = new JDialogFinSubjSaveUpdate(this, true, finSubjectClass, type, finSubj);
        } catch (Exception ex) {
            Logger.getLogger(JFrameFinSubjects.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDialogClientsSaveUpdate.setVisible(true);
    }


    private void jButtonAddClientSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddClientSupplierActionPerformed
        selectedFinSubj = null;
        jDialogFinSubjectsCreateAndShow(jDialogClientsSaveUpdate, finSubjectClass, selectedFinSubj);
        jButtonClearFormActionPerformed(evt);
        selectRowInTable(jTableFinSubjects, jTableFinSubjects.getRowCount() - 1);
    }//GEN-LAST:event_jButtonAddClientSupplierActionPerformed

    private void jButtonRemoveClientSupllierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveClientSupllierActionPerformed
        if (selectedFinSubj != null) {
            int rez = JOptionPane.showConfirmDialog(this, "Are you shure to remove " + selectedFinSubj);
            if (rez == JOptionPane.OK_OPTION) {
                try {
                    int row = jTableFinSubjects.getSelectedRow();
                    finSubjDao.deleteFinSubject(selectedFinSubj);
                    refreshTable(-row - 1, selectedFinSubj);
                } catch (DeletingException ex) {
                    LOG.log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select record to remove");
        }

    }//GEN-LAST:event_jButtonRemoveClientSupllierActionPerformed

    private void refreshTable(int row, FinanceSubject finSubj) {
        aFinSubjTableModel.refreshModel(row, finSubj);
        if (row < 0) {
            {
                row = Math.abs(row) - 1;
            }
        }
        selectRowInTable(jTableFinSubjects, row);
    }

    private void refreshTable(List<FinanceSubject> fsList) {
        aFinSubjTableModel.refreshModel(fsList);
        selectRowInTable(jTableFinSubjects, 0);
    }

    private void refreshTable(int row) {
        aFinSubjTableModel.refreshModel();
        selectRowInTable(jTableFinSubjects, row);
    }

    private void refreshTable(FinanceSubject finSubj) {
        aFinSubjTableModel.refreshModel(finSubj);
        int row = jTableFinSubjects.getRowCount() - 1;
        selectRowInTable(jTableFinSubjects, row);
    }

    private void editFinanceObject(int row) {
        if (selectedFinSubj != null) {
            jDialogFinSubjectsCreateAndShow(jDialogClientsSaveUpdate, finSubjectClass, selectedFinSubj);
//            if (jDialogClientsSaveUpdate != null) {
//                jDialogClientsSaveUpdate = null;
//            }
//            try {
//                jDialogClientsSaveUpdate = new JDialogFinSubjSaveUpdate(this, true, finSubjectClass, "edit", selectedFinSubj);
//                jDialogClientsSaveUpdate.setVisible(true);
            refreshTable(row, selectedFinSubj);
            //jButtonClearActionPerformed(evt);
//            } catch (Exception ex) {
            //              Logger.getLogger(JFrameFinSubjects.class.getName()).log(Level.SEVERE, null, ex);
//            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select record to update");
        }
    }

    private void jButtonEditClientSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditClientSupplierActionPerformed
        int row = jTableFinSubjects.getSelectedRow();
        editFinanceObject(row);
    }//GEN-LAST:event_jButtonEditClientSupplierActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearFormActionPerformed
        jTextFieldAccountClientSupplier.setText("");
        jTextFieldNameClientSupplier.setText("");
        aFinSubjTableModel.refreshModel();
    }//GEN-LAST:event_jButtonClearFormActionPerformed

    private void jTextFieldNameClientSupplierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameClientSupplierKeyReleased
        jTextFieldAccountClientSupplier.setText("");
        List<FinanceSubject> fsList = finSubjDao.findFinSubjectByName(jTextFieldNameClientSupplier.getText());
        refreshTable(fsList);

    }//GEN-LAST:event_jTextFieldNameClientSupplierKeyReleased

    private void jTextFieldAccountClientSupplierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAccountClientSupplierKeyReleased
        jTextFieldNameClientSupplier.setText("");
        String searchLine = jTextFieldAccountClientSupplier.getText();
        if (!searchLine.equals("")) {
            List<FinanceSubject> fsList = finSubjDao.findFinSubjectByAccount(searchLine);
            refreshTable(fsList);
        } else {
            aFinSubjTableModel.refreshModel();
        }
    }//GEN-LAST:event_jTextFieldAccountClientSupplierKeyReleased

    private void jTableFinSubjectsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFinSubjectsMouseReleased

        if (evt.getButton() == MouseEvent.BUTTON3) {
            int selectedRow = jTableFinSubjects.rowAtPoint(evt.getPoint());
            jTableFinSubjects.setRowSelectionInterval(selectedRow, selectedRow);
        }
        if (evt.isPopupTrigger()) {
            jPopupMenuTable.show(jTableFinSubjects, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jTableFinSubjectsMouseReleased

    private void jTableFinSubjectsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFinSubjectsMousePressed
        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1) {
            int selectedRow = jTableFinSubjects.getSelectedRow();
            editFinanceObject(selectedRow);
//            jTableFinSubjects.getCellEditor().cancelCellEditing();
        }
        if (evt.isPopupTrigger()) {
            jPopupMenuTable.show(jTableFinSubjects, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jTableFinSubjectsMousePressed

    private void jMenuItemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddActionPerformed
        jButtonAddClientSupplierActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemAddActionPerformed

    private void jMenuItemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditActionPerformed
        jButtonEditClientSupplierActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemEditActionPerformed

    private void jMenuItemRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoveActionPerformed
        jButtonRemoveClientSupllierActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemRemoveActionPerformed

    private void jTableFinSubjectsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableFinSubjectsKeyReleased
        if (evt.getKeyCode() == 155) {
            jButtonAddClientSupplierActionPerformed(null);
        }
        if (evt.getKeyCode() == 127) {
            jButtonRemoveClientSupllierActionPerformed(null);
        }
    }//GEN-LAST:event_jTableFinSubjectsKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameFinSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameFinSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameFinSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameFinSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrameFinSubjects(Class.forName("com.iucosoft.farmacy.model.Client")).setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(JFrameFinSubjects.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(JFrameFinSubjects.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddClientSupplier;
    private javax.swing.JButton jButtonClearForm;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonEditClientSupplier;
    private javax.swing.JButton jButtonRemoveClientSupllier;
    private javax.swing.JMenuItem jMenuItemAdd;
    private javax.swing.JMenuItem jMenuItemEdit;
    private javax.swing.JMenuItem jMenuItemRemove;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelSearch;
    private javax.swing.JPopupMenu jPopupMenuTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFinSubjects;
    private javax.swing.JTextField jTextFieldAccountClientSupplier;
    private javax.swing.JTextField jTextFieldNameClientSupplier;
    // End of variables declaration//GEN-END:variables
    Class finSubjectClass;
    FinSubjTableModel aFinSubjTableModel;
    FinanceSubjectDaoIntf finSubjDao;
    JDialogFinSubjSaveUpdate jDialogClientsSaveUpdate;
    FinanceSubject selectedFinSubj;
}
